services:
  - type: static_site
    name: code-tracker-web
    env: static
    buildCommand: npm run build
    publishDir: ./dist
    envVars:
      - key: NODE_VERSION
        value: "20"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
